# Generated by Django 3.2.5 on 2021-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento_name', models.CharField(max_length=30)),
                ('marca_name', models.CharField(max_length=30)),
                ('modelo_name', models.CharField(max_length=30)),
                ('macsn_name', models.CharField(max_length=30)),
                ('valor_name', models.CharField(max_length=30)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
