# Generated by Django 3.2.5 on 2021-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0002_auto_20210707_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='valor_name',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
