# Generated by Django 3.2.5 on 2021-07-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0003_alter_cadastro_valor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='equipamento_name',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='marca_name',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='modelo_name',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.categoria'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.marca'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.modelo'),
        ),
    ]
