# Generated by Django 3.2.5 on 2021-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0004_auto_20210707_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
