# Generated by Django 3.2.5 on 2021-07-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0005_cadastro_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_name', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='valor_name',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='valor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.valor'),
        ),
    ]
