# Generated by Django 3.2.5 on 2021-07-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0008_alter_cadastro_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['categoria']},
        ),
    ]
