# Generated by Django 3.2.5 on 2021-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0009_alter_cadastro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['register_date']},
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='register_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
