# Generated by Django 3.2.5 on 2021-07-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0011_alter_cadastro_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macsn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo_name',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='marca_name',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='modelo_name',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='macsn_name',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='macsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.macsn'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='valor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.valor'),
        ),
    ]
