# Generated by Django 3.2.5 on 2021-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0012_auto_20210712_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='tipo_name',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='marca',
            new_name='marca_name',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='modelo',
            new_name='modelo_name',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='macsn',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='macsn_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='Macsn',
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
    ]
