# Generated by Django 3.2.5 on 2021-07-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0014_auto_20210713_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-register_date']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo_name']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['marca_name']},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['modelo_name']},
        ),
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name_plural': 'Situações'},
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.marca'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='modelo_name',
            field=models.CharField(max_length=100),
        ),
    ]
