# Generated by Django 3.2.5 on 2021-07-19 11:38

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0015_auto_20210713_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_name', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['categoria']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['marca_name'], 'verbose_name': 'Marca'},
        ),
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações'},
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='macsn_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Padrão MAC/SN'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='situacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.situacao', verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='imagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcmapp.imagem'),
        ),
    ]
