# Generated by Django 3.2.5 on 2021-07-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcmapp', '0016_auto_20210719_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem_name',
            field=models.ImageField(upload_to='equip'),
        ),
    ]
